const products = [
    {id: 1, name: 'MacBook Air', category: 'mac', price: 999, stock: 3, description: 'Strikingly thin and fast so you can work, play, or create anywhere.'},
    {id: 2, name: 'MacBook Pro', category: 'mac', price: 1599, stock: 5, description: 'The most advanced Mac laptops for demanding workflows.'},
    {id: 3, name: 'iMac', category: 'mac', price: 1299, stock: 8, description: 'A stunning all-in-one desktop for creativity and productivity.'},
    {id: 4, name: 'Mac mini', category: 'mac', price: 599, stock: 2, description: 'The most affordable Mac desktop with outsized performance.'},
    {id: 5, name: 'Mac Studio', category: 'mac', price: 1999, stock: 10, description: 'Powerful performance and extensive connectivity for pro workflows.'},
    {id: 6, name: 'Mac Pro', category: 'mac', price: 6999, stock: 7, description: 'A pro workstation with PCIe expansion for demanding workflows.'},
    {id: 7, name: 'Studio Display', category: 'mac', price: 1599, stock: 5, description: 'A 5K Retina display with stellar camera and audio.'},
    {id: 8, name: 'Pro Display XDR', category: 'mac', price: 4999, stock: 1, description: 'An advanced 6K XDR display for pro workflows.'},
    {id: 9, name: 'iPad Pro', category: 'ipad', price: 799, stock: 6, description: 'The ultimate iPad experience with the most advanced technology.'},
    {id: 10, name: 'iPad Air', category: 'ipad', price: 599, stock: 10, description: 'Serious performance in a thin and light design.'},
    {id: 11, name: 'iPad 10th generation', category: 'ipad', stock: 3, price: 449, description: 'The colorful, all‑screen iPad for the things you do every day.'},
    {id: 12, name: 'iPad 9th generation', category: 'ipad', stock: 8, price: 329, description: 'All the essentials in the most affordable iPad.'},
    {id: 13, name: 'iPad mini', category: 'ipad', price: 499, stock: 15, description: 'The full iPad experience designed to fit in one hand.'},
    {id: 14, name: 'iPhone 15 Pro', category: 'iphone', price: 999, stock: 4, description: 'The ultimate iPhone.'},
    {id: 15, name: 'iPhone 15', category: 'iphone', price: 799, stock: 7, description: 'A total powerhouse.'},
    {id: 16, name: 'iPhone 14', category: 'iphone', price: 699, stock: 14, description: 'As amazing as ever.'},
    {id: 17, name: 'iPhone 13', category: 'iphone', price: 599, stock: 9, description: 'All kinds of awesome.'},
    {id: 18, name: 'iPhone SE', category: 'iphone', price: 429, stock: 5, description: 'Serious power. Serious value.'},
    {id: 19, name: 'Apple Watch Series 9', category: 'watch', price: 399, stock: 5, description: 'All the essentials. Light on price.'},
    {id: 20, name: 'Apple Watch Ultra 2', category: 'watch', price: 799, stock: 6, description: 'Powerful sensors, advanced health features.'},
    {id: 21, name: 'Apple Watch SE', category: 'watch', price: 249, stock: 4, description: 'The most rugged and capable.'},
    {id: 22, name: 'Apple Watch Hermès', category: 'watch', price: 1249, stock: 1, description: 'Exclusive Hermès bands and watch faces.'},
    {id: 23, name: 'Apple Vision Pro', category: 'vision', price: 3499, stock: 2, description: 'Welcome to the era of spatial computing.'},
    {id: 24, name: 'ZEISS Optical Inserts', category: 'vision', price: 99, stock: 4, description: 'Custom made according to your prescription.'},
    {id: 25, name: 'AirPods Pro', category: 'airpods', price: 249, stock: 20, description: 'Up to 2x more Active Noise Cancellation.'},
    {id: 26, name: 'AirPods 3rd generation', category: 'airpods', stock: 17, price: 169, description: 'Taking sound in totally new directions.'},
    {id: 27, name: 'AirPods 2nd generation', category: 'airpods', stock: 15, price: 129, description: 'Wireless. Effortless. Magical.'},
    {id: 28, name: 'AirPods Max', category: 'airpods', price: 549, stock: 10, description: 'The ultimate personal listening experience is here.'},
    {id: 29, name: 'Apple TV 4K', category: 'tvhome', price: 129, stock: 5, description: 'The ultimate TV experience is calling.'},
    {id: 30, name: 'HomePod mini', category: 'tvhome', price: 99, stock: 6, description: 'Surprising sound for its size.'},
    {id: 31, name: 'HomePod', category: 'tvhome', price: 299, stock: 8, description: 'Profound sound.'},
    {id: 32, name: 'Siri Remote', category: 'tvhome', price: 59, stock: 2, description: 'The Siri Remote brings precise control to your Apple TV 4K.'}
]

export default products